# -*- coding: utf-8 -*-
"""
Created on Thu Aug 12 11:21:38 2021

@author: Raman Sewjugath
"""

print("Task 1")

# Initialize the variable "result" as a string so string additions can occur and not numerical data types
# this allows the output values to be concatenated as a string and not calculated as in 1+1 = 2, rather, "1" +" 1" = 1 1
result=""

# the for loop iterates as x =1 through to 9, 
for x in range(1,10):

  '''
  and y iterates 1 through the value of x (as x iterates from 1 to 9)
  The loop does not initialize when x = 1, and result = "", because the end index is 1 and not included
  to factor for this, added 1 to x, so when x = 1, x+1 = 2, and this loop will inialize for index 1.
  '''
  for y in range(1,x+1):

    # each time a result is generated by the loop it is concatenated to result, building the string
    result += str(x*y) + " "  

   # the final string is printed to the console
  print(result)  

  # this sets the value of the string to null, so that the next iteration wont build on the previous one           
  result=""                 